# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: LaunchBuildVM
  timeoutInMinutes: 10
  pool:
    name: Autodesk
    demands: hypervisor
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Start-Vm -Name Revit_2018
        $VM = Get-VM -Name Revit_2018
        while ($VM.State -ne 'Running')
        {
            $VM = Get-VM -Name Revit_2018
            Start-Sleep -s 15
        }
      
        write-host "The VM is on"

- job: Build
  strategy:
    matrix:     
      2018:
        vmName: 'Revit_2018'  
  continueOnError: true
  timeoutInMinutes: 10
  pool:
    name: Autodesk
    demands: Revit  -equals 2018
  steps:
  - task: VSBuild@1
    inputs:
      solution: '**\*.sln'
      clean: true
      restoreNugetPackages: true
      msbuildArchitecture: 'x64'

- job: StopBuildVM
  dependsOn: Build
  timeoutInMinutes: 10
  pool:
    name: Autodesk
    demands: hypervisor
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Stop-Vm -Name Revit_2018 -TurnOff
        Restore-VMSnapshot -Name 'Base' -VMName Revit_2018  -Confirm:$false