# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Autodesk
  demands: hypervisor

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Start-Vm -Name Revit_2021
      $VM = Get-VM -Name Revit_2021
      while ($VM.State -ne 'Running')
      {
          $VM = Get-VM -Name Revit_2021
          Start-Sleep -s 15
      }
      
      write-host "The VM is on"
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Stop-Vm -Name Revit_2021 -TurnOff
      Restore-VMSnapshot -Name 'Base' -VMName Revit_2021  -Confirm:$false