<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\BaseProject.csproj" />
	<PropertyGroup>
		<RootNamespace>JPP.Cedar.Rosetta</RootNamespace>
		<Company>JPP Consulting</Company>
	</PropertyGroup>
	<ItemGroup>
	  <ProjectReference Include="..\StructuralAnalysis\StructuralAnalysis.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="RevitAPI">
			<HintPath>..\..\..\..\..\..\..\Program Files\Autodesk\Revit 2025\RevitAPI.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>
</Project>
