jobs:
- job: Package
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
      2021:      
        poolFlag: 2021
        framework: net48
      2020:
        poolFlag: 2020
        framework: net47
      2019:
        poolFlag: 2019
        framework: net47
  dependsOn: Build
  steps:      
  - checkout: none
  - download: current
    artifact: Build $(poolFlag)
  - powershell: |
      New-Item -Path "$(System.DefaultWorkingDirectory)" -Name "installpackage" -ItemType "directory"
      Get-ChildItem -Recurse * | Where-Object {$_.FullName.EndsWith("$(framework)") -and $_.FullName.Contains("bin") -and !$_.FullName.Contains("Test")} | Copy-Item -Destination $(System.DefaultWorkingDirectory)\installpackage -force -recurse   
      Rename-Item $(System.DefaultWorkingDirectory)\installpackage\$(framework) $(System.DefaultWorkingDirectory)\installpackage\Cedar      
      Get-ChildItem -Exclude Cedar $(System.DefaultWorkingDirectory)\installpackage | Remove-Item -Recurse -Force
      Copy-Item Cedar.addin -Destination $(System.DefaultWorkingDirectory)\installpackage -force    
    workingDirectory: $(Pipeline.Workspace)\Build $(poolFlag)
    displayName: 'Copy Files'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)\installpackage' 
      includeRootFolder: false
      archiveType: 'zip' # Options: zip, 7z, tar, wim      
      archiveFile: '$(Build.ArtifactStagingDirectory)\$(Build.BuildId).zip'       
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: Install Package $(poolFlag)        
  - task: AzureFileCopy@4
    inputs:
      sourcePath: '$(Build.ArtifactStagingDirectory)\$(Build.BuildId).zip'
      azureSubscription: MLSub
      destination: azureBlob
      storage: jppcdnstorage
      containerName: cedar
      blobPrefix: $(Build.SourceBranch)/$(poolFlag)/$(Build.BuildId).zip