<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\BaseProject.csproj" />

  <PropertyGroup>
    <RootNamespace>JPP.Cedar</RootNamespace>
    <Company>JPP Consulting</Company>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <PropertyGroup>
    <PostBuildEvent>xcopy "$(SolutionDir)src\Cedar\Cedar.addin" "C:\ProgramData\Autodesk\Revit\Addins\$(RevitVersion)" /Y /C

xcopy "$(TargetDir)*" "C:\ProgramData\Autodesk\Revit\Addins\$(RevitVersion)\Cedar" /S /Y /I</PostBuildEvent>
    <SignAssembly>false</SignAssembly>
    <DelaySign>false</DelaySign>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CedarCore\CedarCore.csproj" />
    <ProjectReference Include="..\Piling\Piling.csproj" />
    <ProjectReference Include="..\Rosetta\Rosetta.csproj" />
	<FrameworkReference Include="Microsoft.WindowsDesktop.App" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RevitAPI">
      <HintPath>..\..\..\..\..\..\..\Program Files\Autodesk\Revit 2025\RevitAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>..\..\..\..\..\..\..\Program Files\Autodesk\Revit 2025\RevitAPIUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>