trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - master
    - release/*
      
jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:     
      2021:
        poolFlag: 2021
      2020:
        poolFlag: 2020
      2019:
        poolFlag: 2019
  steps:  
  - template: pipelinetemplates/build.yml
    parameters:
      SolutionName: 'Cedar'    
      Build: 'Release'
      PoolFlag: $(poolFlag)
